### ISSUE TITLE
any idea why this does not work with create-react-app?

### ISSUE THREAD

**Issue by thg303** [rstacruz/jsdom-global#21]
I made `src/setupTests.js` with:
`import 'jsdom-global/register'`

but when jest runs, it shows this error:
```
/home/ali/projects/x_project/x/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:75
      throw new TypeError("Argument to dispatchEvent must be an Event");
      ^
TypeError: Argument to dispatchEvent must be an Event
    at EventTargetImpl.dispatchEvent (/home/ali/projects/x_project/x/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:75:13)
    at Window.dispatchEvent (/home/ali/projects/x_project/x/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
    at Window.process.nextTick (/home/ali/projects/x_project/x/node_modules/jsdom/lib/jsdom/browser/Window.js:492:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rstacruz** [comment]
There's no need to use this for jest or create-react-app. Jest already comes preloaded with a jsdom environment.

**Comment by thg303** [comment]
so you mean I could have `document.styleSheets[0]` in my source and there would no problem with it?

**Comment by rstacruz** [comment]
Yep! http://facebook.github.io/jest/docs/configuration.html#testenvironment-string

**Comment by thg303** [comment]
wow man! this error took all my day! I was moving to karma from jest because of `Enzyme.mount` function. wow! I don't know javascript any more...
